# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3be08605dffd97f20b218fa266f5e7b3305ff835a7858a44b965798c7fff42b2702a7070dd561fe8c8d768ab865694516bbc1a01b5337ff64becfc5d4459765

test:
  secret_key_base: 1c494ddfc99991a9901db9c3b9808782f8ed0167b6d204634407172fe2771620de976bd9a1ce98a6e0893cea045ff7eab9afd26358726bfa9bd03fcdb953277a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
